[theme]
primaryColor = "#e94a35"
backgroundColor = "#fbfaf5"
secondaryBackgroundColor = "#f3f0e8"
textColor = "#16201e"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

